FROM ubuntu:22.04
MAINTAINER Marco Poletti <poletti.marco@gmail.com>

COPY common_install.sh common_cleanup.sh /

RUN bash -x /common_install.sh

COPY ubuntu-22.04_custom.list /etc/apt/sources.list.d/

RUN apt-get update

RUN apt-get remove -y python3-pip

RUN apt-get install -y --allow-unauthenticated --no-install-recommends \
        g++-9 \
        g++-10 \
        g++-11 \
        g++-12 \
        clang-11 \
        clang-12 \
        clang-13 \
        clang-14 \
        clang-15 \
        python3 \
        python3-distutils \
        python3-pip \
        clang-tidy \
        clang-format

RUN pip3 install absl-py
RUN pip3 install bidict
RUN pip3 install pytest
RUN pip3 install pytest-xdist
RUN pip3 install sh
RUN pip3 install setuptools
RUN pip3 install networkx
RUN pip3 install wheel

RUN bash -x /common_cleanup.sh
