FROM ubuntu:24.04
MAINTAINER Marco Poletti <poletti.marco@gmail.com>

COPY common_install.sh common_cleanup.sh /

RUN bash -x /common_install.sh

COPY ubuntu-24.04_custom.list /etc/apt/sources.list.d/

RUN apt-get update

RUN apt-get install -y --allow-unauthenticated --no-install-recommends \
        g++-9 \
        g++-10 \
        g++-11 \
        g++-12 \
        g++-13 \
        g++-14 \
        clang-14 \
        clang-15 \
        clang-16 \
        clang-17 \
        clang-18 \
        python3 \
        python3-absl \
        python3-bidict \
        python3-networkx \
        python3-pytest \
        python3-pytest-xdist \
        python3-setuptools \
        python3-sh \
        python3-wheel \
        clang-tidy \
        clang-format

RUN bash -x /common_cleanup.sh
