FROM ubuntu:19.10
MAINTAINER Marco Poletti <poletti.marco@gmail.com>

COPY common_install.sh common_cleanup.sh /

RUN bash -x /common_install.sh

COPY ubuntu-19.10_custom.list /etc/apt/sources.list.d/

RUN apt-get update

RUN apt-get install -y --allow-unauthenticated --no-install-recommends \
        g++-7 \
        g++-8 \
        g++-9 \
        clang-6.0 \
        clang-7 \
        clang-8 \
        clang-9 \
        clang-10 \
        python3-sh \
        python3-typed-ast \
        python3-pip \
        python3-setuptools \
        python3-networkx \
        clang-tidy \
        clang-format

RUN pip3 install --upgrade pip

RUN pip3 install absl-py
RUN pip3 install bidict
RUN pip3 install pytest
RUN pip3 install pytest-xdist
RUN pip3 install sh
RUN pip3 install setuptools
RUN pip3 install networkx
RUN pip3 install wheel

RUN bash -x /common_cleanup.sh
