load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "com_google_googletest",
    remote = "https://github.com/google/googletest",
    # GTest HEAD as of August 2018.
    commit = "9c96f500a39df6915f8f1ab53b60be9889f1572b",
)
